function [data] = CEA_Rocket(ox,fuel,pct,O_F,epsilon,Tox,Tf)

reactants =   [                                           ...
             CEA.Reactant(fuel,                           ...
                     'Type','Fuel',                     ...
                     'T',DimVar(Tf,'K'),             ...         
                     'Q',DimVar(1,'kg'))                ...
            CEA.Reactant(ox,                            ...
                    'Type','ox',                        ...
                    'T',DimVar(Tox,'K'),              ...         
                    'Q',DimVar(1,'kg'))                 ...
            ];     
        

data =  CEA.Run(reactants,                                ...
        'ProblemType','Rocket',                         ...
        'Flow','eq',                                 ...
        'Pc',DimVar(pct,'Pa'),                           ...
        'OF',O_F,'supar',epsilon,                                         ...
        'Outputs',{'isp','t','cf','p'});
